name: Build metrics
on:
  schedule: [{ cron: "30 23 * * 0" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 1523fff022a1c1038e8d57353472ae1a
          user: loicreynier
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Paris
          plugin_habits: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming
          plugin_languages_details: percentage,lines
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          # plugin_leetcode: yes
          # plugin_leetcode_sections: skills
      - name: Stack Overflow metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stackoverflow.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 1523fff022a1c1038e8d57353472ae1a
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 22158873
          plugin_stackoverflow_sections: answers-top
